// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkO0ggihotufWSr_hQFi5LEHdI7uXveN8',
    appId: '1:807369736427:web:36fa1735c0551de2523eae',
    messagingSenderId: '807369736427',
    projectId: 'vamo-rachar-d0a09',
    authDomain: 'vamo-rachar-d0a09.firebaseapp.com',
    storageBucket: 'vamo-rachar-d0a09.firebasestorage.app',
    measurementId: 'G-NLKXD3848S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMqdVQJsQOquHzIYo2KhGPyuIE6HQ-wME',
    appId: '1:807369736427:android:8b8989c09c99b93b523eae',
    messagingSenderId: '807369736427',
    projectId: 'vamo-rachar-d0a09',
    storageBucket: 'vamo-rachar-d0a09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3miSTPw1BEC0G69x3F9RnIilQc3BV9Jk',
    appId: '1:807369736427:ios:a8e6fb2930463182523eae',
    messagingSenderId: '807369736427',
    projectId: 'vamo-rachar-d0a09',
    storageBucket: 'vamo-rachar-d0a09.firebasestorage.app',
    iosBundleId: 'com.example.vamorachar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3miSTPw1BEC0G69x3F9RnIilQc3BV9Jk',
    appId: '1:807369736427:ios:a8e6fb2930463182523eae',
    messagingSenderId: '807369736427',
    projectId: 'vamo-rachar-d0a09',
    storageBucket: 'vamo-rachar-d0a09.firebasestorage.app',
    iosBundleId: 'com.example.vamorachar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkO0ggihotufWSr_hQFi5LEHdI7uXveN8',
    appId: '1:807369736427:web:bf89235c35a0409d523eae',
    messagingSenderId: '807369736427',
    projectId: 'vamo-rachar-d0a09',
    authDomain: 'vamo-rachar-d0a09.firebaseapp.com',
    storageBucket: 'vamo-rachar-d0a09.firebasestorage.app',
    measurementId: 'G-TV1E5WYBDB',
  );
}
